Add English readme
gosha-krovsh/freedom pull request #76
Opened 2021-10-24 18:51 UTC by ArseniyTy

2021-10-24 19:23 UTC, gosha-krovsh requested changes
Круто, классно. Вот то, что мне не понравилось

2021-10-24 19:23 UTC, gosha-krovsh commented on README.md
> +do is break down the thick walls or kill all the guards. Talk to your
`break` -> `to break`
`kill` -> `to kill`

2021-10-24 19:23 UTC, gosha-krovsh commented on README.md
> +* The system of __quests and dialogues__ allows you to create very flexible storylines.
`very flexible` не звучит как по мне, но ладно
Можно просто `flexible`

2021-10-24 19:23 UTC, gosha-krovsh commented on README.md
> +* All animation, appearance of game objects and characters were developed at
`appearance` мне не нрав. Можно `textures`

2021-10-24 19:23 UTC, gosha-krovsh commented on README.md
> +* The architecture of the application is based on the pattern __MVC__ (Model-View-Controller).
pattern MVC < MVC pattern
Я бы перевернул слова местами

2021-10-24 19:23 UTC, gosha-krovsh commented on README.md
> +* The `resources.qrc` file was used for resource management, and `.json` files were used for data storage and __serialization/deserialization__ systems. Usage of `json-`s significantly increased the
- Или `as data storage`
  Или `to store data`
  + И тоже самое к serialization
- `raised the speed` звучит круче
  А также вместо концовки `features(quests ...) filling rate` лучше

2021-10-24 19:23 UTC, gosha-krovsh commented on README.md
> +* А __flexible animation system__ of game objects allows you to animate objects by absolutely any state.
С концовкой беды. `by absolutely any state`  прям что-то неее, это прям неправильно даже с точки зрения языка. Напиши точно, что ты хотел сказать

2021-10-25 16:46 UTC, ArseniyTy commented on README.md
> +* The `resources.qrc` file was used for resource management, and `.json` files were used for data storage and __serialization/deserialization__ systems. Usage of `json-`s significantly increased the
Мне кажется, что со скоростью чаще используется глагол "increase".
И я не оч понял про последнее предложение, напиши плиз итоговый вариант

2021-10-25 16:48 UTC, ArseniyTy commented on README.md
> +* А __flexible animation system__ of game objects allows you to animate objects by absolutely any state.
Так посмотри русскую версию, там оно так и переводится) Вопрос в том, что даже на русском звучит не оч понятно для человека, не посвящённого в тему. Но это про то, что мы там в темплейт могли кидать разные штуки как состояния анимации. Можно конечно написать, что это опять же очень "flexible", но уже до этого много такого написано

2021-10-25 16:50 UTC, ArseniyTy commented on README.md
> +do is break down the thick walls or kill all the guards. Talk to your
Можно и так и так. Но текущий вариант даже [больше юзается](https://english.stackexchange.com/questions/104546/all-you-have-to-do-is-read-vs-all-you-have-to-do-is-to-read):

2021-10-25 16:55 UTC, gosha-krovsh commented on README.md
> +* А __flexible animation system__ of game objects allows you to animate objects by absolutely any state.
Ну блин, тут сложно придумать нормальный вариант. `Any state parameter can be used to animate object`
Но тут хз

2021-10-25 16:57 UTC, gosha-krovsh commented on README.md
> +* The `resources.qrc` file was used for resource management, and `.json` files were used for data storage and __serialization/deserialization__ systems. Usage of `json-`s significantly increased the
А мне raise нравится, но в принципе и так пойдет. Я бы концовку поменял только
Можно вместо `and...` -> `and content(quests ...) filling rate`

2021-10-25 16:58 UTC, gosha-krovsh commented on README.md
> +do is break down the thick walls or kill all the guards. Talk to your
Уничтожил, ладно. Я просто не люблю форму с просто инфинитивом...

2021-10-25 17:18 UTC, gosha-krovsh approved these changes

2021-10-25 17:26 UTC, HydeHunter2 approved these changes

2021-10-25 17:29 UTC, merged